spring:
  application:
    name: place-service
  profiles:
    active:
      - local
    group:
      local:
        - db-local
        - eureka-local
      prod:
        - db-prod
        - eureka-prod
    include:
      - db
      - eureka
server:
  port: 8088
