spring:
  application:
    name: user-service
  profiles:
    active:
        - prod
    group:
      local:
        - db-local
        - eureka-local
        - security-local
      prod:
        - db-prod
        - eureka-prod
        - security-prod
    include:
      - db
      - eureka
      - security
  mvc:
    static-path-pattern: /static/**


server:
  #port: 0
  port: 8087